repos:
  - repo: https://github.com/mineiros-io/pre-commit-hooks
    rev: v0.4.1
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
        exclude: ^examples|.terraform/
      - id: tflint
      - id: phony-targets
      - id: terradoc-validate
      - id: golangci-lint
      - id: terradoc-fmt
      - id: terradoc-generate
      # - id: terramate-generate
      - id: markdown-link-check
        args: ['-p']   # When adding the -p flag, markdown-link-check will always with an exit code 0, even if dead links are found
        verbose: true  # Forces the output of the hook to be printed even when the hook passes.
