// AsciiDoc TOC settings
:toc:
:toc-placement!:
:toc-title:

// GitHub Flavored Asciidoc (GFA). See https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74 for details.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= terraform-github-organization

image:https://img.shields.io/badge/maintained%20by-mineiros.io-%235849a6.svg[Maintained by Mineiros.io, link="https://www.mineiros.io/ref=repo_terraform-github-organization"]
image:https://mineiros.semaphoreci.com/badges/terraform-github-organization/branches/master.svg?style=shields[Build Status, link="https://mineiros.semaphoreci.com/projects/terraform-github-organization"]
image:https://img.shields.io/github/v/tag/mineiros-io/terraform-github-organization.svg?label=latest&sort=semver[GitHub tag (latest Semantic Version), link="https://github.com/mineiros-io/terraform-github-organization/releases"]
image:https://img.shields.io/badge/tf-%3E%3D0.12.9-blue.svg[Terraform Version]

[.lead]
A Terraform module that acts as a wrapper around the Terraform https://www.terraform.io/docs/providers/github/index.html[GitHub provider]
and offers a more convenient and tested way to manage GitHub Organizations following best practices.

[NOTE]
====
This module allows you to manage your GitHub organization's members settings easily.
It needs to be configured with the proper credentials before it can be used and it cannot be use to provision new organizations since this is not supported by the Terraform https://www.terraform.io/docs/providers/github/index.html[GitHub provider].
====

[TIP]
====
This Module uses `For, For-Each and Dynamic Nested Blocks` that were introduced in Terraform 0.12.
A common problem in Terraform configurations for versions 0.11 and earlier is dealing with situations where the number of values or resources is decided by a dynamic expression rather than a fixed count.

You can now dynamically add and remove items from and to Lists without the necessity to render the whole list of resources again.
Terraform will only add and remove the items you want it to.
====

== Table of Contents
toc::[]

== Requirements
* Terraform `~> 0.12.9` - for full resource `for_each` support
* Terraform GitHub provider `~> 2.2`

== Features
This module uses https://github.com/terraform-providers/terraform-provider-github/releases[Terraform GitHub provider v2.2.x] that supports the following resources:

=== Standard github provider features
* :heavy_check_mark: Organization Members
* :heavy_check_mark: Organization Owners (Admins)
* :heavy_check_mark: Organization Projects
* :heavy_check_mark: Blocked Users
* :x: Organization Webhooks (not yet implemented)

=== Additional module features
* :heavy_check_mark: Change organization member roles without removing and re-inviting users
* :heavy_check_mark: Rename projects without recreating (when providing unique ids)
* :heavy_check_mark: No need to import members/admins on first run

== Usage
[source,hcl]
----
module "organization" {
  source = "git::git::git@github.com:mineiros-io/terraform-github-organization.git?ref=master"

  members = [
    "a-user",
    "b-user",
  ]

  admins = [
    "a-admin",
  ]

  blocked_users = [
    "blocked-user",
    "another-blocked-user",
  ]

  projects = [
    {
      id   = "project-a"
      name = "A Great Project"
      body = "This is a project created by Terraform"
    }
  ]
}
----

[TIP]
====
Note for 0.0.x versions: in a production environment you most likely want to stick to a specific version of this module instead of the master
branch (e.g. ?ref=v0.0.1), because there may be breaking changes between releases.
====

=== Examples
For a complete example please see link:/examples[examples] directory.

=== Tests
This modules ships with a link:Makefile[Makefile] and a link:Dockerfile[Dockerfile] that simplify executing the hooks
and tests for you.

Execute all pre-commit hooks with Docker:
[source,shell script]
----
make docker-run-pre-commit-hooks
----

Execute the Unit Test (deploy and undeploy the example):
[source,shell script]
----
GITHUB_ORGANIZATION=YOUR_GITHUB_ORGANIZATION \
GITHUB_TOKEN=YOUR_GITHUB_TOKEN \
make docker-run-tests
----

== Limitations
- Currently the https://www.terraform.io/docs/providers/github/index.html[GitHub Provider] doesn't support to provision new organizations.

//:sourcedir: examples/organization
//
//[source,hcl-terraform]
//----
//include::{sourcedir}/main.tf[]
//----
