name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run pre-commit
        run: make test/pre-commit

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Unit Tests
        run: make test/unit-tests
        env:
          GITHUB_OWNER: ${{ secrets.TEST_GITHUB_ORGANIZATION }}
          GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
